spring:
    jackson:
      serialization: false
      default-property-inclusion: always
    thymeleaf:
        cache: false
        prefix: classpath:/templates/
        encoding: utf-8
        content-type: application/alto-endpointcostparams+json
logging:
  config: classpath:logback-spring.xml


---

spring:
  profiles:
    active: dev
  redis:
    host: 119.23.20.12
    port: 6379
    password: 123456
    timeout: 2000
    max-active: 8
    max-idle: 8
    max-wait: -1
    min-idle: 0
    database: 0
  activemq:
    broker-url: tcp://119.23.20.12:61616
    user: admin
    password: 123456admin
    pool:
      enabled: true
      max-connections: 50
      expiry-timeout: 10000
      idle-timeout: 30000
  jms:
    pub-sub-domain: true
server:
  port: 8888
  context-path: /api/
asyncSetter:
  timeout: 5
mq:
  topic: com.roc.topic
  queue: com.roc.queue



---
spring:
  profiles:
    active: prd
  redis:
    host: 119.23.20.12
    port: 6379
    password: 123456
    timeout: 2000
    max-active: 8
    max-idle: 8
    max-wait: -1
    min-idle: 0
    database: 0
  activemq:
    broker-url: tcp://119.23.20.12:61616
    user: admin
    password: 123456admin
    pool:
      enabled: true
      max-connections: 50
      expiry-timeout: 10000
      idle-timeout: 30000
  jms:
    pub-sub-domain: true
server:
  port: 8888
  context-path: /api/
asyncSetter:
  timeout: 5
mq:
  topic: com.roc.topic
  queue: com.roc.queue
---